let gameSq = [];
let userSq = [];

let btns = ["yellow", "red", "purple", "green"];

let started = false;
let level = 0;
let highScore=0;

let h2 = document.querySelector('h2');
let h3 = document.querySelector('h3');
document.addEventListener("keypress", function () {
    if (started == false) {
        started = true;
        levelUp();
    }
});

function gameFlash(btn) {
    btn.classList.add("flash");

    setTimeout(function () {
        btn.classList.remove("flash");
    }, 250);
}

function userFlash(btn) {
    btn.classList.add("userFlash");

    setTimeout(function () {
        btn.classList.remove("userFlash");
    }, 250);
}
function levelUp() {
    userSq = [];
    level++;
    h2.innerText = `Level ${level}`;
    let randIdx = Math.floor(Math.random() * 4);
    let randColor = btns[randIdx];
    let randBtn = document.querySelector(`.${randColor}`);    // Btn generated by game
    gameSq.push(randColor);
    gameFlash(randBtn);
}

function checkAns(idx) {
    if (gameSq[idx] === userSq[idx]) {
        if (userSq.length == gameSq.length) {
            setTimeout(levelUp, 700);
        }
    } else {
        if(level>highScore) {
            highScore=level;
        }
        h3.innerHTML = `<b>High score ${highScore}</b>`;
        h2.innerHTML = `Game Over! Your score was <b>${level}</b> <br> Press any key to start`;
        document.querySelector("body").style.backgroundColor = "red";
        setTimeout(function () {
            document.querySelector("body").style.backgroundColor = "white";
        }, 200);
        reset();
    }
}
function btnPress() {    // Btn pressed by user
    let btn = this;
    userFlash(btn);

    let userColor = btn.getAttribute("id");
    userSq.push(userColor);
    checkAns(userSq.length - 1);
}
let allBtns = document.querySelectorAll('.btn');
for (let btn of allBtns) {
    btn.addEventListener("click", btnPress);
}

function reset() {
    started = false;
    gameSq = [];
    userSq = [];
    level = 0;
}