let gameSq = [];
let userSq = [];

let btns = ["yellow", "red", "purple", "green"];

let started = false;
let level = 0;

let h2 = document.querySelector('h2');

document.addEventListener("keypress", function () {
    if (started == false) {
        started = true;
        levelUp();
    }
});

function gameFlash(btn) {
    btn.classList.add("flash");

    setTimeout(function () {
        btn.classList.remove("flash");
    }, 250);
}

function userFlash(btn) {
    btn.classList.add("userFlash");

    setTimeout(function () {
        btn.classList.remove("userFlash");
    }, 250);
}
function levelUp() {
    userSq=[];
    level++;
    h2.innerText = `Level ${level}`;

    let randIdx = Math.floor(Math.random() * 4);      
    let randColor = btns[randIdx];
    let randBtn = document.querySelector(`.${randColor}`);    // Btn generated by game
    gameSq.push(randColor);
    gameFlash(randBtn);
}

function checkAns(idx) {
      if(gameSq[idx]===userSq[idx]) {
        if(userSq.length==gameSq.length) {
            setTimeout(levelUp, 1000);
        }
      } else {
        h2.innerText=`Game Over! Press any key to start`;
        reset();
      }
}
function btnPress() {    // Btn pressed by user
    let btn = this;
    userFlash(btn);

    userColor=btn.getAttribute("id");
    userSq.push(userColor);
    checkAns(userSq.length-1);
}
let allBtns = document.querySelectorAll('.btn');
for (btn of allBtns) {
    btn.addEventListener("click", btnPress);
}

function reset() {
    started=false;
    gameSq=[];
    userSq=[];
    level=0;
}